### ISSUE TITLE
data-ng-submit on view1.html

### ISSUE THREAD

**Issue by rhgksrua** [pknelakuditi/PollApp#8]
The form tag has `data-gn-submit` attribute.  This attribute will fire off `pc.submitNewPoll()` whenever a button inside form tag is clicked.  This includes the choices add button.  So whenever a user clicks on add, it also sends an ajax request to the server.  We only want to send ajax request when submit is clicked.  We need to either move the `pc.submitNewPoll()` to the submit button, or move the add button outside the form.

**Comment by pknelakuditi** [comment]
adding type="button" would fix the issue. browsers are taking default type pf button as submit is the cause for this issue.
